[package]
name         = "aloo-vuln"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
description  = "Vulnerability correlation engine for Aloo"

[dependencies]
aloo-core   = { workspace = true }
aloo-traits = { workspace = true }
tokio       = { workspace = true }
async-trait = { workspace = true }
thiserror   = { workspace = true }
tracing     = { workspace = true }
serde       = { workspace = true }
