[package]
name         = "aloo-config"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
description  = "Configuration loading and validation for Aloo"

[dependencies]
aloo-core  = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
toml       = { workspace = true }
thiserror  = { workspace = true }
ipnet      = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
