[package]
name         = "aloo-probes"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
description  = "Protocol probe implementations for Aloo"

[dependencies]
aloo-core   = { workspace = true }
aloo-traits = { workspace = true }
aloo-net    = { workspace = true }
tokio       = { workspace = true }
async-trait = { workspace = true }
bytes       = { workspace = true }
thiserror   = { workspace = true }
tracing     = { workspace = true }
