//! `aloo-report` — Report generation for scan results.
//!
//! Provides JSON, HTML, and Markdown reporters, each implementing the
//! [`Reporter`] trait from `aloo-traits`.

#![forbid(unsafe_code)]
#![warn(missing_docs)]

use aloo_core::ScanResult;
use aloo_traits::{OutputFormat, ReportError, Reporter};
use async_trait::async_trait;

// ── JSON Reporter ─────────────────────────────────────────────────────────────

/// Serialises a `ScanResult` to JSON.
pub struct JsonReporter {
    /// If true, emit pretty-printed JSON.
    pub pretty: bool,
}

impl JsonReporter {
    /// Create a compact JSON reporter.
    pub fn compact() -> Self {
        Self { pretty: false }
    }

    /// Create a pretty-printed JSON reporter.
    pub fn pretty() -> Self {
        Self { pretty: true }
    }
}

impl Default for JsonReporter {
    fn default() -> Self {
        Self::compact()
    }
}

#[async_trait]
impl Reporter for JsonReporter {
    fn format(&self) -> OutputFormat {
        OutputFormat::Json
    }

    async fn render_to_string(&self, result: &ScanResult) -> Result<String, ReportError> {
        let s = if self.pretty {
            serde_json::to_string_pretty(result)
        } else {
            serde_json::to_string(result)
        }
        .map_err(|e| ReportError::Serialisation(e.to_string()))?;
        Ok(s)
    }
}

// ── HTML Reporter ─────────────────────────────────────────────────────────────

/// Renders a `ScanResult` as an HTML report.
pub struct HtmlReporter;

impl HtmlReporter {
    /// Build the HTML skeleton for a scan result.
    fn build_html(result: &ScanResult) -> String {
        let host_count  = result.hosts.len();
        let open_ports  = result.total_open_ports();
        let vuln_count  = result.total_vulnerabilities();
        let session_id  = &result.session.id;
        let started_at  = result.session.started_at.format("%Y-%m-%d %H:%M:%S UTC");
        let status      = format!("{:?}", result.session.status);

        format!(
            r#"<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Aloo Scan Report — {session_id}</title>
  <style>
    body {{ font-family: sans-serif; background: #0f0f13; color: #e0e0e0; margin: 2rem; }}
    h1   {{ color: #7ec8e3; }}
    table {{ border-collapse: collapse; width: 100%; }}
    td, th {{ border: 1px solid #333; padding: 0.5rem 1rem; }}
    th   {{ background: #1a1a2e; }}
    .open {{ color: #4caf50; }}
    .vuln {{ color: #f44336; }}
  </style>
</head>
<body>
  <h1>Aloo Network Intelligence Report</h1>
  <h2>Session: {session_id}</h2>
  <p>Started: {started_at} | Status: {status}</p>
  <table>
    <tr><th>Metric</th><th>Value</th></tr>
    <tr><td>Hosts discovered</td><td>{host_count}</td></tr>
    <tr><td>Open ports</td><td class="open">{open_ports}</td></tr>
    <tr><td>Vulnerabilities</td><td class="vuln">{vuln_count}</td></tr>
  </table>
  <p><em>Generated by Aloo v0.1.0</em></p>
</body>
</html>"#
        )
    }
}

#[async_trait]
impl Reporter for HtmlReporter {
    fn format(&self) -> OutputFormat {
        OutputFormat::Html
    }

    async fn render_to_string(&self, result: &ScanResult) -> Result<String, ReportError> {
        Ok(Self::build_html(result))
    }
}

// ── Markdown Reporter ─────────────────────────────────────────────────────────

/// Renders a `ScanResult` as a Markdown summary.
pub struct MarkdownReporter;

impl MarkdownReporter {
    fn build_markdown(result: &ScanResult) -> String {
        let mut md = String::new();
        md.push_str("# Aloo Scan Report\n\n");
        md.push_str(&format!("**Session ID:** `{}`\n\n", result.session.id));
        md.push_str(&format!(
            "**Started:** {}  \n**Status:** {:?}\n\n",
            result.session.started_at.format("%Y-%m-%d %H:%M:%S UTC"),
            result.session.status,
        ));

        md.push_str("## Summary\n\n");
        md.push_str(&format!("| Metric | Value |\n|--------|-------|\n"));
        md.push_str(&format!("| Hosts  | {} |\n", result.hosts.len()));
        md.push_str(&format!("| Open Ports | {} |\n", result.total_open_ports()));
        md.push_str(&format!("| Vulnerabilities | {} |\n\n", result.total_vulnerabilities()));

        if result.hosts.is_empty() {
            md.push_str("_No hosts discovered._\n");
        } else {
            md.push_str("## Hosts\n\n");
            for host in &result.hosts {
                md.push_str(&format!(
                    "### {}\n",
                    host.hostname.as_deref().unwrap_or(&host.ip.to_string())
                ));
                md.push_str(&format!("- **IP:** `{}`\n", host.ip));
                md.push_str(&format!("- **Open ports:** {}\n\n",
                    host.ports.iter().filter(|p| p.state == aloo_core::PortState::Open).count()
                ));
            }
        }
        md
    }
}

#[async_trait]
impl Reporter for MarkdownReporter {
    fn format(&self) -> OutputFormat {
        OutputFormat::Markdown
    }

    async fn render_to_string(&self, result: &ScanResult) -> Result<String, ReportError> {
        Ok(Self::build_markdown(result))
    }
}

// ── Report dispatcher ─────────────────────────────────────────────────────────

/// Dispatches rendering to the appropriate reporter based on format.
pub struct ReportDispatcher {
    reporters: Vec<Box<dyn Reporter>>,
}

impl ReportDispatcher {
    /// Create with all built-in reporters.
    pub fn with_all() -> Self {
        Self {
            reporters: vec![
                Box::new(JsonReporter::compact()),
                Box::new(HtmlReporter),
                Box::new(MarkdownReporter),
            ],
        }
    }

    /// Render using the reporter matching `format`.
    pub async fn render(
        &self,
        format: OutputFormat,
        result: &ScanResult,
    ) -> Result<String, ReportError> {
        for r in &self.reporters {
            if r.format() == format {
                return r.render_to_string(result).await;
            }
        }
        Err(ReportError::Template(format!("No reporter for format {:?}", format)))
    }
}

impl Default for ReportDispatcher {
    fn default() -> Self {
        Self::with_all()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use aloo_core::ScanSession;

    fn empty_result() -> ScanResult {
        let mut s = ScanSession::new(vec!["10.0.0.0/24".into()]);
        s.complete();
        ScanResult { session: s, hosts: vec![] }
    }

    #[tokio::test]
    async fn json_reporter_produces_valid_json() {
        let result = empty_result();
        let s = JsonReporter::compact().render_to_string(&result).await.unwrap();
        let v: serde_json::Value = serde_json::from_str(&s).expect("must be valid JSON");
        assert!(v.is_object());
    }

    #[tokio::test]
    async fn json_reporter_pretty_contains_newlines() {
        let result = empty_result();
        let s = JsonReporter::pretty().render_to_string(&result).await.unwrap();
        assert!(s.contains('\n'));
    }

    #[tokio::test]
    async fn html_reporter_contains_doctype() {
        let result = empty_result();
        let s = HtmlReporter.render_to_string(&result).await.unwrap();
        assert!(s.starts_with("<!DOCTYPE html>"));
        assert!(s.contains("Aloo"));
    }

    #[tokio::test]
    async fn markdown_reporter_starts_with_heading() {
        let result = empty_result();
        let s = MarkdownReporter.render_to_string(&result).await.unwrap();
        assert!(s.starts_with("# Aloo Scan Report"));
    }

    #[tokio::test]
    async fn dispatcher_json() {
        let d = ReportDispatcher::with_all();
        let result = empty_result();
        let s = d.render(OutputFormat::Json, &result).await.unwrap();
        assert!(serde_json::from_str::<serde_json::Value>(&s).is_ok());
    }
}
