[package]
name         = "aloo-fingerprint"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
description  = "Service and OS fingerprinting engine for Aloo"

[dependencies]
aloo-core   = { workspace = true }
aloo-traits = { workspace = true }
regex       = { workspace = true }
tracing     = { workspace = true }
